version: "3.0"
services:
  ubuntu:
    image: ubuntu:gui
    hostname: dev
    user: user
    working_dir: /home/user
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host