version: "3.0"
services:
  ros2:
    image: humble:dev
    hostname: dev
    user: user
    working_dir: /home/user
    stdin_open: true
    tty: true 
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/user/ros2_ws:/home/user/ros2_ws
      - /dev/shm:/dev/shm
    network_mode: host